### ISSUE TITLE
Force hex field as string type not binary type

### ISSUE THREAD

**Issue by tbhaxor** [go-testfixtures/testfixtures#148]
I have a hex field in the yaml which I want textfixture should interpret it as a string not binary field

```yaml
- addr: 0x6C1DB75D8b4f588ea23ed401528c808e09Bdb611
  active: true
  created: 1982-11-04T14:29:32.463320184Z
  modified: 1982-11-04T14:29:32.463320184Z
  user_id: 1148427545745236030
```

I have tried enclosing in quotes, but it didnt work
