### ISSUE TITLE
CLI not working anymore on docker compose + M1 chip

### ISSUE THREAD

**Issue by Jerome1337** [go-testfixtures/testfixtures#149]
I run the CLI inside a docker compose container on a 2021 M1 chip macbook pro but recently I get this error and I'm not able anymore to run the command

```sh
 qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
```

Here is an example of the container

```yaml
fixtures:
  container_name: "load-fixtures"
  image: golang:1.19-alpine
  working_dir: /data
  env_file:
    - .env
  volumes:
    - "./fixtures:/data/fixtures"
    - "./scripts/load-fixtures.sh:/data/load-fixtures.sh"
  entrypoint: ["./load-fixtures.sh"]
  depends_on:
    - db
```

When I run this container and install the testfixtures binary using wget and latest release, I get the error above.

I test using `alpine` and `golang` alpine images without success.

Version used:
- `testfixtures v3.8.1`
- `docker 20.10.21`
- `docker compose 2.12.2`
- `alpine 3.17`
