### ISSUE TITLE
JSON supports

### ISSUE THREAD

**Issue by lunny** [go-testfixtures/testfixtures#6]
It would be better if you can support the following format.

```yml
-
  id: 1
  slice_of_struct:
     -
       name: myname1
       value: myvalue1
     -
       name: myname2
       value: myvalue2
```
