### ISSUE TITLE
Error "pq: unsupported jsonb version number 123"

### ISSUE THREAD

**Issue by rezikovka** [go-testfixtures/testfixtures#83]
Hi! In YAML i configured an object
```
- order_code: 123456
  created_at: 2020-11-19 12:29:10
  updated_at: 2020-11-19 12:38:36
  data:
      AfterUpdateData: 
        PickupTimestamp: 2020-11-24T08:34:25.46251+03:00
        AtClientTimestamp: 2020-11-19T15:38:35.806412+03:00
        AtVendorTimestamp: 2020-11-24T08:34:25.46251+03:00
      BeforeUpdateData: 
        PickupTimestamp: 2020-11-24T08:34:25.46251+03:00
        AtClientTimestamp: 2020-11-24T08:34:25.46251+03:00
        AtVendorTimestamp: 2020-11-24T08:34:25.46251+03:00
```
Appliyng of this fixture leads to an error
```
testfixtures: error inserting record: pq: unsupported jsonb version number 123, on file: delivery.yml, index: 0, sql: INSERT INTO "delivery" ("order_code", "created_at", "updated_at", "data") VALUES ($1, $2, $3, $4), params: [123456 2020-11-19 12:29:10 +0300 MSK 2020-11-19 12:38:36 +0300 MSK map[AfterUpdateData:map[AtClientTimestamp:2020-11-19T15:38:35.806412+03:00 AtVendorTimestamp:2020-11-24T08:34:25.46251+03:00 PickupTimestamp:2020-11-24T08:34:25.46251+03:00] BeforeUpdateData:map[AtClientTimestamp:2020-11-24T08:34:25.46251+03:00 AtVendorTimestamp:2020-11-24T08:34:25.46251+03:00 PickupTimestamp:2020-11-24T08:34:25.46251+03:00]]]
```
Same problem described here https://github.com/lib/pq/issues/528 . The solution - to cast []byte or json.RawMessage to string before inserting. Is it possible?
