### ISSUE TITLE
How do I seed multiple tables from a single file?

### ISSUE THREAD

**Issue by fr3fou** [go-testfixtures/testfixtures#98]
Ideally I want to be able to do
```yaml
# TestUserService_OnePost.yaml
users:
    - id: 2
      name: Joe
posts:
    - id: 1
      user_id: 2
      content: "hi"
```

The example in the README shows you have to make one file per table, what I want is to have individual files for each test case which contain all the necessary data for each table as shown in the example. Currently I've been using https://github.com/romanyx/polluter which does the job but isn't maintained. I'd like to migrate to this eventually.
